<?php
declare(strict_types=1);
require_once __DIR__.'/auth.php';
$config=__DIR__.'/config/database.php'; $error=''; $done=false;
if (!is_file($config)) $error='Database configuration is not ready yet. Complete hosting/database setup first.';
else { require $config; $count=(int)$pdo->query('SELECT COUNT(*) FROM users')->fetchColumn(); if($count>0){http_response_code(403);exit('Initial setup is locked because an account already exists.');} }
if ($_SERVER['REQUEST_METHOD']==='POST' && !$error) {
 if(!verify_csrf((string)($_POST['csrf']??''))) $error='Session expired. Please try again.';
 else {
  $business=trim((string)($_POST['business_name']??''));$name=trim((string)($_POST['name']??''));$username=trim((string)($_POST['username']??''));$password=(string)($_POST['password']??'');
  if(!$business||!$name||!$username||strlen($password)<8)$error='Complete all fields. Password must be at least 8 characters.';
  else { $slug=preg_replace('/[^a-z0-9]+/','-',strtolower($business));$slug=trim($slug?:'business','-').'-'.substr(bin2hex(random_bytes(3)),0,6);$pdo->beginTransaction();try{$s=$pdo->prepare('INSERT INTO businesses(business_name,slug) VALUES(?,?)');$s->execute([$business,$slug]);$bid=(int)$pdo->lastInsertId();$s=$pdo->prepare("INSERT INTO users(business_id,name,username,password_hash,role) VALUES(?,?,?,?, 'owner')");$s->execute([$bid,$name,$username,password_hash($password,PASSWORD_DEFAULT)]);$pdo->commit();$done=true;}catch(Throwable $e){$pdo->rollBack();$error='Setup could not be completed.';} }
 }
}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MeroKhata Setup</title><style>body{font-family:Arial;background:#f3f6fa;padding:30px;color:#172033}.box{max-width:560px;margin:auto;background:white;padding:28px;border-radius:15px;box-shadow:0 8px 30px #0001}label{display:block;font-weight:bold;margin-top:14px}input{width:100%;box-sizing:border-box;padding:12px;margin-top:5px;border:1px solid #ccd3dd;border-radius:8px}button{margin-top:20px;padding:12px 20px;border:0;border-radius:8px;background:#174f9b;color:white;font-weight:bold}.note{padding:11px;background:#eef5ff;border-radius:8px}.err{padding:11px;background:#fff0f0;color:#991b1b;border-radius:8px}</style></head><body><div class="box"><h1>MeroKhata Initial Setup</h1><?php if($done):?><div class="note"><b>Owner account created.</b> Setup is now locked. <a href="login.php">Go to Login</a>.</div><?php else:?><p class="note">Run this only once after the database is ready. It creates the first business and owner account. No default password is stored in GitHub.</p><?php if($error):?><p class="err"><?=htmlspecialchars($error)?></p><?php endif;?><form method="post"><input type="hidden" name="csrf" value="<?=htmlspecialchars(csrf_token())?>"><label>Business Name</label><input name="business_name" required><label>Owner Name</label><input name="name" required><label>Username</label><input name="username" required autocomplete="username"><label>Password (minimum 8 characters)</label><input name="password" type="password" minlength="8" required autocomplete="new-password"><button>Create First Owner Account</button></form><?php endif;?></div></body></html>