<?php
declare(strict_types=1);
require_once __DIR__.'/auth.php';
$config=__DIR__.'/config/database.php';$error='';$done=false;$companyCode='';
if(!is_file($config))$error='Database configuration is not ready yet. Complete hosting/database setup first.';
else{require $config;$count=(int)$pdo->query('SELECT COUNT(*) FROM businesses')->fetchColumn();if($count>0){http_response_code(403);exit('Initial company setup is locked. Future companies must be created by the MeroKhata system administrator.');}}
if($_SERVER['REQUEST_METHOD']==='POST'&&!$error){
 if(!verify_csrf((string)($_POST['csrf']??'')))$error='Session expired. Please try again.';
 else{$business=trim((string)($_POST['business_name']??''));$code=strtolower(trim((string)($_POST['company_code']??'')));$address=trim((string)($_POST['address']??''));$phone=trim((string)($_POST['phone']??''));$pan=trim((string)($_POST['pan_vat']??''));$name=trim((string)($_POST['name']??''));$username=trim((string)($_POST['username']??''));$password=(string)($_POST['password']??'');$code=preg_replace('/[^a-z0-9-]+/','-',$code);$code=trim((string)$code,'-');
  if(!$business||!$code||!$name||!$username||strlen($password)<8)$error='Complete all required fields. Password must be at least 8 characters.';
  else{$pdo->beginTransaction();try{$s=$pdo->prepare('INSERT INTO businesses(business_name,slug,address,phone,pan_vat) VALUES(?,?,?,?,?)');$s->execute([$business,$code,$address?:null,$phone?:null,$pan?:null]);$bid=(int)$pdo->lastInsertId();$s=$pdo->prepare("INSERT INTO users(business_id,name,username,password_hash,role) VALUES(?,?,?,?, 'owner')");$s->execute([$bid,$name,$username,password_hash($password,PASSWORD_DEFAULT)]);$pdo->commit();$done=true;$companyCode=$code;}catch(Throwable $e){$pdo->rollBack();$error='Company setup could not be completed. Company Code may already exist.';}}
 }
}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MeroKhata Admin Setup</title><style>body{font-family:Arial;background:#f3f6fa;padding:30px;color:#172033}.box{max-width:650px;margin:auto;background:white;padding:28px;border-radius:15px;box-shadow:0 8px 30px #0001}.grid{display:grid;grid-template-columns:1fr 1fr;gap:0 16px}label{display:block;font-weight:bold;margin-top:14px}input{width:100%;box-sizing:border-box;padding:12px;margin-top:5px;border:1px solid #ccd3dd;border-radius:8px}button{margin-top:20px;padding:12px 20px;border:0;border-radius:8px;background:#174f9b;color:white;font-weight:bold}.note{padding:11px;background:#eef5ff;border-radius:8px}.err{padding:11px;background:#fff0f0;color:#991b1b;border-radius:8px}@media(max-width:650px){.grid{grid-template-columns:1fr}}</style></head><body><div class="box"><h1>MeroKhata — First Company Setup</h1><?php if($done):?><div class="note"><b>Company and Owner Login created successfully.</b><br>Company Code: <b><?=htmlspecialchars($companyCode)?></b><br><br>Keep this Company Code with the username and password. <a href="login.php">Go to Login</a>.</div><?php else:?><p class="note"><b>Admin first:</b> Enter the company details and create its Owner Login. Login becomes usable only after this setup. Future companies will be created separately by the MeroKhata system administrator in the same way.</p><?php if($error):?><p class="err"><?=htmlspecialchars($error)?></p><?php endif;?><form method="post"><input type="hidden" name="csrf" value="<?=htmlspecialchars(csrf_token())?>"><h3>Company Details</h3><div class="grid"><label>Business / Company Name *<input name="business_name" required></label><label>Company Code *<input name="company_code" required placeholder="e.g. maikot"></label><label>Address<input name="address"></label><label>Phone<input name="phone"></label><label>PAN/VAT No.<input name="pan_vat"></label></div><h3>Owner Login</h3><div class="grid"><label>Owner Name *<input name="name" required></label><label>Username *<input name="username" required autocomplete="username"></label><label>Password (minimum 8 characters) *<input name="password" type="password" minlength="8" required autocomplete="new-password"></label></div><button>Save Company & Create Owner Login</button></form><?php endif;?></div></body></html>