const KEY='maikotBusinessDemoV1';
const state=JSON.parse(localStorage.getItem(KEY)||'{"products":[],"suppliers":[],"purchases":[],"sales":[]}');
state.sales=state.sales||[];
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const money=v=>'Rs. '+Number(v||0).toLocaleString(undefined,{maximumFractionDigits:2});
const byId=(arr,id)=>arr.find(x=>String(x.id)===String(id));
function uid(arr){return arr.length?Math.max(...arr.map(x=>Number(x.id)||0))+1:1}
function esc(s){return String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function showPanel(id,btn){document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');pageTitle.textContent=btn.textContent.trim();renderAll()}
document.querySelectorAll('.nav button').forEach(b=>b.addEventListener('click',()=>showPanel(b.dataset.panel,b)));
function conv(p){return +p.units_per_unit||1}
function baseQty(p){return (+p.qty||0)*conv(p)}
function purchaseNet(p){return (+p.qty*+p.purchase_rate)-(+p.discount||0)+(+p.transport||0)+(+p.other_cost||0)}
function actual(p){const q=baseQty(p);return q?purchaseNet(p)/q:0}
function productPurchases(productId){return state.purchases.filter(p=>String(p.product_id)===String(productId))}
function productSales(productId){return state.sales.filter(s=>String(s.product_id)===String(productId))}
function purchasedQty(productId){return productPurchases(productId).reduce((a,p)=>a+baseQty(p),0)}
function soldQty(productId){return productSales(productId).reduce((a,s)=>a+(+s.qty||0),0)}
function avgCost(productId){const rows=productPurchases(productId),qty=rows.reduce((a,p)=>a+baseQty(p),0);return qty?rows.reduce((a,p)=>a+purchaseNet(p),0)/qty:0}
function currentStock(productId){return purchasedQty(productId)-soldQty(productId)}
function stockValueFor(productId){return currentStock(productId)*avgCost(productId)}
function isLowStock(product){const level=+product.reorder_level||0;return level>0&&currentStock(product.id)<=level}
function todayISO(){return new Date().toISOString().slice(0,10)}
function renderDashboard(){productsCount.textContent=state.products.length;suppliersCount.textContent=state.suppliers.length;purchasesCount.textContent=state.purchases.length;totalPurchase.textContent=money(state.purchases.reduce((a,p)=>a+purchaseNet(p),0));totalStockQty.textContent=state.products.reduce((a,p)=>a+currentStock(p.id),0).toLocaleString(undefined,{maximumFractionDigits:2});stockValue.textContent=money(state.products.reduce((a,p)=>a+stockValueFor(p.id),0));todaySoldQty.textContent=state.sales.filter(s=>s.sale_date===todayISO()).reduce((a,s)=>a+(+s.qty||0),0).toLocaleString(undefined,{maximumFractionDigits:2});lowStockCount.textContent=state.products.filter(isLowStock).length}
function renderProducts(){productBody.innerHTML=state.products.map(p=>`<tr><td>${esc(p.product_code)}</td><td>${esc(p.product_name)}</td><td>${esc(p.category)}</td><td>${esc(p.brand_model)}</td><td>${esc(p.unit)}</td><td>${money(p.selling_price)}</td><td>${+p.reorder_level||0}</td><td><button onclick="delProduct(${p.id})">Delete</button></td></tr>`).join('')}
function renderSuppliers(){supplierBody.innerHTML=state.suppliers.map(s=>`<tr><td>${esc(s.supplier_code)}</td><td>${esc(s.supplier_name)}</td><td>${esc(s.contact_person)}</td><td>${esc(s.phone)}</td><td>${esc(s.address)}</td><td><button onclick="delSupplier(${s.id})">Delete</button></td></tr>`).join('')}
function renderSelects(){const cp=purchaseProduct?.value||'',cs=purchaseSupplier?.value||'',cc=compareProduct?.value||'',csp=saleProduct?.value||'';purchaseProduct.innerHTML='<option value="">Select product</option>'+state.products.map(p=>`<option value="${p.id}">${esc(p.product_name)}</option>`).join('');purchaseSupplier.innerHTML='<option value="">Select supplier</option>'+state.suppliers.map(s=>`<option value="${s.id}">${esc(s.supplier_name)}</option>`).join('');compareProduct.innerHTML='<option value="">Select product</option>'+state.products.map(p=>`<option value="${p.id}">${esc(p.product_name)}</option>`).join('');saleProduct.innerHTML='<option value="">Select product</option>'+state.products.map(p=>`<option value="${p.id}">${esc(p.product_name)}</option>`).join('');if([...purchaseProduct.options].some(o=>o.value===cp))purchaseProduct.value=cp;if([...purchaseSupplier.options].some(o=>o.value===cs))purchaseSupplier.value=cs;if([...compareProduct.options].some(o=>o.value===cc))compareProduct.value=cc;if([...saleProduct.options].some(o=>o.value===csp))saleProduct.value=csp}
function renderPurchases(){purchaseBody.innerHTML=[...state.purchases].reverse().map(p=>{const pr=byId(state.products,p.product_id),su=byId(state.suppliers,p.supplier_id);return `<tr><td>${esc(p.purchase_date)}</td><td>${esc(pr?.product_name||'')}</td><td>${esc(su?.supplier_name||'')}</td><td>${p.qty} ${esc(p.purchase_unit||pr?.unit||'Unit')}</td><td>${baseQty(p).toLocaleString(undefined,{maximumFractionDigits:2})} ${esc(pr?.unit||'')}</td><td>${money(p.purchase_rate)}</td><td>${money(actual(p))}</td><td><button onclick="delPurchase(${p.id})">Delete</button></td></tr>`}).join('')}
function renderSales(){salesBody.innerHTML=[...state.sales].reverse().map(s=>{const pr=byId(state.products,s.product_id);return `<tr><td>${esc(s.sale_date)}</td><td>${esc(pr?.product_name||'')}</td><td>${s.qty}</td><td>${esc(pr?.unit||'')}</td><td>${money(s.selling_rate)}</td><td>${money((+s.qty||0)*(+s.selling_rate||0))}</td><td><button onclick="delSale(${s.id})">Delete</button></td></tr>`}).join('')}
function renderStock(){stockBody.innerHTML=state.products.map(p=>{const pq=purchasedQty(p.id),sq=soldQty(p.id),stock=currentStock(p.id),cost=avgCost(p.id),value=stockValueFor(p.id),low=isLowStock(p);return `<tr><td>${esc(p.product_code)}</td><td>${esc(p.product_name)}</td><td>${esc(p.unit)}</td><td>${pq.toLocaleString(undefined,{maximumFractionDigits:2})}</td><td>${sq.toLocaleString(undefined,{maximumFractionDigits:2})}</td><td><b>${stock.toLocaleString(undefined,{maximumFractionDigits:2})}</b></td><td>${money(cost)}</td><td>${money(value)}</td><td>${+p.reorder_level||0}</td><td>${low?'⚠️ Low Stock':'✅ OK'}</td></tr>`}).join('')}
function renderComparison(){if(!compareProduct.value){comparisonBody.innerHTML='';return}const rows=state.purchases.filter(p=>String(p.product_id)===String(compareProduct.value)).sort((a,b)=>actual(a)-actual(b));comparisonBody.innerHTML=rows.map((p,i)=>{const s=byId(state.suppliers,p.supplier_id),pr=byId(state.products,p.product_id);return `<tr><td>${esc(p.purchase_date)}</td><td>${esc(s?.supplier_name||'')}${i===0?' ⭐':''}</td><td>${p.qty} ${esc(p.purchase_unit||pr?.unit||'Unit')}</td><td>${baseQty(p).toLocaleString(undefined,{maximumFractionDigits:2})} ${esc(pr?.unit||'')}</td><td>${money(p.purchase_rate)}</td><td>${money(actual(p))}</td></tr>`}).join('')}
function renderAll(){renderDashboard();renderProducts();renderSuppliers();renderSelects();renderPurchases();renderSales();renderStock();renderComparison();if(!purchaseDate.value)purchaseDate.value=todayISO();if(!saleDate.value)saleDate.value=todayISO()}
productForm.addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(productForm));if(state.products.some(x=>x.product_code.trim().toLowerCase()===d.product_code.trim().toLowerCase()))return alert('Product code already exists.');state.products.push({id:uid(state.products),...d,selling_price:+d.selling_price||0,reorder_level:+d.reorder_level||0});save();productForm.reset();productForm.unit.value='Piece';productForm.reorder_level.value='0';renderAll()});
supplierForm.addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(supplierForm));if(state.suppliers.some(x=>x.supplier_code.trim().toLowerCase()===d.supplier_code.trim().toLowerCase()))return alert('Supplier code already exists.');state.suppliers.push({id:uid(state.suppliers),...d});save();supplierForm.reset();renderAll()});
purchaseUnit.addEventListener('change',()=>{if(purchaseUnit.value==='Dozen')unitsPerUnit.value=12;else if(purchaseUnit.value==='Pair')unitsPerUnit.value=2;else unitsPerUnit.value=1});
purchaseForm.addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(purchaseForm));state.purchases.push({id:uid(state.purchases),...d,product_id:+d.product_id,supplier_id:+d.supplier_id,qty:+d.qty,units_per_unit:+d.units_per_unit||1,purchase_rate:+d.purchase_rate,discount:+d.discount||0,transport:+d.transport||0,other_cost:+d.other_cost||0});save();purchaseForm.reset();purchaseDate.value=todayISO();purchaseUnit.value='Piece';unitsPerUnit.value='1';renderAll()});
salesForm.addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(salesForm)),pid=+d.product_id,qty=+d.qty||0,stock=currentStock(pid);if(qty>stock)return alert(`Not enough stock. Current stock: ${stock}`);const pr=byId(state.products,pid);state.sales.push({id:uid(state.sales),sale_date:d.sale_date,product_id:pid,qty,selling_rate:+d.selling_rate||(+pr?.selling_price||0)});save();salesForm.reset();saleDate.value=todayISO();renderAll()});
saleProduct.addEventListener('change',()=>{const p=byId(state.products,+saleProduct.value);if(p)salesForm.selling_rate.value=+p.selling_price||0});
compareProduct.addEventListener('change',renderComparison);
window.delProduct=id=>{if(state.purchases.some(p=>p.product_id===id)||state.sales.some(s=>s.product_id===id))return alert('This product has purchase/sales records. Delete those first.');if(confirm('Delete this product?')){state.products=state.products.filter(x=>x.id!==id);save();renderAll()}};
window.delSupplier=id=>{if(state.purchases.some(p=>p.supplier_id===id))return alert('This supplier has purchase records. Delete those first.');if(confirm('Delete this supplier?')){state.suppliers=state.suppliers.filter(x=>x.id!==id);save();renderAll()}};
window.delPurchase=id=>{if(confirm('Delete this purchase entry?')){state.purchases=state.purchases.filter(x=>x.id!==id);save();renderAll()}};
window.delSale=id=>{if(confirm('Delete this sales entry?')){state.sales=state.sales.filter(x=>x.id!==id);save();renderAll()}};
loadSampleBtn.addEventListener('click',()=>{if(state.products.length||state.suppliers.length||state.purchases.length||state.sales.length){if(!confirm('Replace current demo data with sample data?'))return}state.products=[{id:1,product_code:'P001',product_name:'Ball Pen',category:'Stationery',brand_model:'Generic',unit:'Piece',selling_price:20,reorder_level:12},{id:2,product_code:'P002',product_name:'4 in 1 Notebook',category:'Stationery',brand_model:'Kids Practice',unit:'Piece',selling_price:180,reorder_level:10}];state.suppliers=[{id:1,supplier_code:'S001',supplier_name:'Wholesale Supplier A',contact_person:'',phone:'',address:'Kathmandu',pan_vat:''},{id:2,supplier_code:'S002',supplier_name:'Wholesale Supplier B',contact_person:'',phone:'',address:'Kathmandu',pan_vat:''}];state.purchases=[{id:1,purchase_date:todayISO(),product_id:1,supplier_id:1,qty:3,purchase_unit:'Dozen',units_per_unit:12,purchase_rate:120,discount:0,transport:0,other_cost:0},{id:2,purchase_date:todayISO(),product_id:2,supplier_id:2,qty:20,purchase_unit:'Piece',units_per_unit:1,purchase_rate:120,discount:0,transport:50,other_cost:0}];state.sales=[{id:1,sale_date:todayISO(),product_id:1,qty:5,selling_rate:20}];save();renderAll()});
resetBtn.addEventListener('click',()=>{if(confirm('Delete all demo data saved in this browser?')){state.products=[];state.suppliers=[];state.purchases=[];state.sales=[];save();renderAll()}});
renderAll();