const KEY='maikotBusinessDemoV1';
const state=JSON.parse(localStorage.getItem(KEY)||'{"products":[],"suppliers":[],"purchases":[]}');
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const money=v=>'Rs. '+Number(v||0).toLocaleString(undefined,{maximumFractionDigits:2});
const byId=(arr,id)=>arr.find(x=>String(x.id)===String(id));
function uid(arr){return arr.length?Math.max(...arr.map(x=>Number(x.id)||0))+1:1}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function showPanel(id,btn){document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');pageTitle.textContent=btn.textContent.trim();renderAll()}
document.querySelectorAll('.nav button').forEach(b=>b.addEventListener('click',()=>showPanel(b.dataset.panel,b)));
function actual(p){return ((+p.qty*+p.purchase_rate)-(+p.discount||0)+(+p.transport||0)+(+p.other_cost||0))/(+p.qty||1)}
function renderDashboard(){productsCount.textContent=state.products.length;suppliersCount.textContent=state.suppliers.length;purchasesCount.textContent=state.purchases.length;totalPurchase.textContent=money(state.purchases.reduce((a,p)=>a+(+p.qty*+p.purchase_rate)-(+p.discount||0)+(+p.transport||0)+(+p.other_cost||0),0))}
function renderProducts(){productBody.innerHTML=state.products.map(p=>`<tr><td>${esc(p.product_code)}</td><td>${esc(p.product_name)}</td><td>${esc(p.category)}</td><td>${esc(p.brand_model)}</td><td>${esc(p.unit)}</td><td>${money(p.selling_price)}</td><td><button onclick="delProduct(${p.id})">Delete</button></td></tr>`).join('')}
function renderSuppliers(){supplierBody.innerHTML=state.suppliers.map(s=>`<tr><td>${esc(s.supplier_code)}</td><td>${esc(s.supplier_name)}</td><td>${esc(s.contact_person)}</td><td>${esc(s.phone)}</td><td>${esc(s.address)}</td><td><button onclick="delSupplier(${s.id})">Delete</button></td></tr>`).join('')}
function renderPurchaseSelects(){purchaseProduct.innerHTML='<option value="">Select product</option>'+state.products.map(p=>`<option value="${p.id}">${esc(p.product_name)}</option>`).join('');purchaseSupplier.innerHTML='<option value="">Select supplier</option>'+state.suppliers.map(s=>`<option value="${s.id}">${esc(s.supplier_name)}</option>`).join('');compareProduct.innerHTML='<option value="">Select product</option>'+state.products.map(p=>`<option value="${p.id}">${esc(p.product_name)}</option>`).join('')}
function renderPurchases(){purchaseBody.innerHTML=[...state.purchases].reverse().map(p=>{const pr=byId(state.products,p.product_id),su=byId(state.suppliers,p.supplier_id),ac=actual(p),profit=(+pr?.selling_price||0)-ac;return `<tr><td>${esc(p.purchase_date)}</td><td>${esc(pr?.product_name||'')}</td><td>${esc(su?.supplier_name||'')}</td><td>${p.qty}</td><td>${money(p.purchase_rate)}</td><td>${money(ac)}</td><td>${money(pr?.selling_price)}</td><td>${money(profit)}</td><td><button onclick="delPurchase(${p.id})">Delete</button></td></tr>`}).join('')}
function renderComparison(){if(!compareProduct.value){comparisonBody.innerHTML='';return}const rows=state.purchases.filter(p=>String(p.product_id)===String(compareProduct.value)).sort((a,b)=>actual(a)-actual(b));comparisonBody.innerHTML=rows.map((p,i)=>{const s=byId(state.suppliers,p.supplier_id);return `<tr><td>${esc(p.purchase_date)}</td><td>${esc(s?.supplier_name||'')}${i===0?' ⭐':''}</td><td>${p.qty}</td><td>${money(p.purchase_rate)}</td><td>${money(p.discount)}</td><td>${money((+p.transport||0)+(+p.other_cost||0))}</td><td>${money(actual(p))}</td></tr>`}).join('')}
function renderAll(){renderDashboard();renderProducts();renderSuppliers();renderPurchaseSelects();renderPurchases();renderComparison();if(!purchaseDate.value)purchaseDate.value=new Date().toISOString().slice(0,10)}
productForm.addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(productForm));if(state.products.some(x=>x.product_code.trim().toLowerCase()===d.product_code.trim().toLowerCase()))return alert('Product code already exists.');state.products.push({id:uid(state.products),...d,selling_price:+d.selling_price||0});save();productForm.reset();productForm.unit.value='Piece';renderAll()});
supplierForm.addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(supplierForm));if(state.suppliers.some(x=>x.supplier_code.trim().toLowerCase()===d.supplier_code.trim().toLowerCase()))return alert('Supplier code already exists.');state.suppliers.push({id:uid(state.suppliers),...d});save();supplierForm.reset();renderAll()});
purchaseForm.addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(purchaseForm));state.purchases.push({id:uid(state.purchases),...d,product_id:+d.product_id,supplier_id:+d.supplier_id,qty:+d.qty,purchase_rate:+d.purchase_rate,discount:+d.discount||0,transport:+d.transport||0,other_cost:+d.other_cost||0});save();purchaseForm.reset();purchaseDate.value=new Date().toISOString().slice(0,10);renderAll()});
compareProduct.addEventListener('change',renderComparison);
window.delProduct=id=>{if(state.purchases.some(p=>p.product_id===id))return alert('This product has purchase records. Delete those first.');if(confirm('Delete this product?')){state.products=state.products.filter(x=>x.id!==id);save();renderAll()}};
window.delSupplier=id=>{if(state.purchases.some(p=>p.supplier_id===id))return alert('This supplier has purchase records. Delete those first.');if(confirm('Delete this supplier?')){state.suppliers=state.suppliers.filter(x=>x.id!==id);save();renderAll()}};
window.delPurchase=id=>{if(confirm('Delete this purchase entry?')){state.purchases=state.purchases.filter(x=>x.id!==id);save();renderAll()}};
loadSampleBtn.addEventListener('click',()=>{if(state.products.length||state.suppliers.length||state.purchases.length){if(!confirm('Replace current demo data with sample data?'))return}state.products=[{id:1,product_code:'P001',product_name:'A4 Paper 70 GSM',category:'Stationery',brand_model:'Generic',unit:'Ream',selling_price:550},{id:2,product_code:'P002',product_name:'4 in 1 Notebook',category:'Stationery',brand_model:'Kids Practice',unit:'Piece',selling_price:180},{id:3,product_code:'P003',product_name:'3 in 1 Pen',category:'Stationery',brand_model:'Multi-use',unit:'Piece',selling_price:120}];state.suppliers=[{id:1,supplier_code:'S001',supplier_name:'Wholesale Supplier A',contact_person:'',phone:'',address:'Kathmandu',pan_vat:''},{id:2,supplier_code:'S002',supplier_name:'Wholesale Supplier B',contact_person:'',phone:'',address:'Kathmandu',pan_vat:''},{id:3,supplier_code:'S003',supplier_name:'Wholesale Supplier C',contact_person:'',phone:'',address:'Kathmandu',pan_vat:''}];state.purchases=[{id:1,purchase_date:'2026-09-01',product_id:1,supplier_id:1,qty:10,purchase_rate:480,discount:0,transport:100,other_cost:0},{id:2,purchase_date:'2026-09-03',product_id:1,supplier_id:2,qty:20,purchase_rate:465,discount:200,transport:150,other_cost:0},{id:3,purchase_date:'2026-09-04',product_id:2,supplier_id:1,qty:25,purchase_rate:120,discount:100,transport:0,other_cost:50}];save();renderAll()});
resetBtn.addEventListener('click',()=>{if(confirm('Delete all demo data saved in this browser?')){state.products=[];state.suppliers=[];state.purchases=[];save();renderAll()}});
renderAll();