/* Demo v1.9 extension: Party/Customer master, due ledger and payment modes.
   Uses the same maikotBusinessDemoV1 localStorage data; existing records are preserved. */
state.parties=state.parties||[];state.payments=state.payments||[];save();
let editingPartyId=null;
function nextPartyCode(){const nums=state.parties.map(p=>parseInt(String(p.party_code||'').replace(/\D/g,''))||0);return 'PTY-'+String((nums.length?Math.max(...nums):0)+1).padStart(3,'0')}
function salePaid(s){if(s.paid_amount!=null)return +s.paid_amount||0;if(String(s.payment_type||'').toLowerCase()==='credit')return 0;return saleTotal(s)}
function saleDue(s){if(s.due_amount!=null)return Math.max(0,+s.due_amount||0);return Math.max(0,saleTotal(s)-salePaid(s))}
function salesForParty(p){return state.sales.filter(s=>String(s.party_id||'')===String(p.id)||(!s.party_id&&String(s.customer_name||'').trim().toLowerCase()===String(p.party_name||'').trim().toLowerCase()))}
function receivedForParty(id){return state.payments.filter(x=>String(x.party_id)===String(id)).reduce((a,x)=>a+(+x.amount||0),0)}
function partyDue(p){return Math.max(0,(+p.opening_balance||0)+salesForParty(p).reduce((a,s)=>a+saleDue(s),0)-receivedForParty(p.id))}
function renderPartySelects(){const current=billPartySelect.value,payCurrent=paymentParty.value;billPartySelect.innerHTML='<option value="">Cash Customer / Walk-in</option>'+state.parties.map(p=>`<option value="${p.id}">${esc(p.party_code)} — ${esc(p.party_name)} (Due ${money(partyDue(p))})</option>`).join('');paymentParty.innerHTML='<option value="">Select Party</option>'+state.parties.map(p=>`<option value="${p.id}">${esc(p.party_code)} — ${esc(p.party_name)} | Due ${money(partyDue(p))}</option>`).join('');if([...billPartySelect.options].some(o=>o.value===current))billPartySelect.value=current;if([...paymentParty.options].some(o=>o.value===payCurrent))paymentParty.value=payCurrent;partyList.innerHTML=state.parties.map(p=>`<option value="${esc(p.party_name)}">`).join('')}
function renderParties(){partyBody.innerHTML=state.parties.map(p=>`<tr><td><b>${esc(p.party_code)}</b></td><td>${esc(p.party_name)}</td><td>${esc(p.phone||'')}</td><td>${esc(p.address||'')}</td><td>${esc(p.pan_vat||'')}</td><td><b>${money(partyDue(p))}</b></td><td><button onclick="editParty(${p.id})">Edit</button> <button onclick="viewPartyLedger(${p.id})">Ledger</button> <button onclick="delParty(${p.id})">Delete</button></td></tr>`).join('');paymentBody.innerHTML=[...state.payments].reverse().map(x=>{const p=byId(state.parties,x.party_id);return `<tr><td>${esc(x.payment_date)}</td><td>${esc(p?.party_name||'')}</td><td>${esc(x.mode||'Cash')}</td><td>${esc(x.reference||'-')}${x.bank_wallet?`<br><small>${esc(x.bank_wallet)}</small>`:''}</td><td><b>${money(x.amount)}</b></td><td>${esc(x.note||'')}</td></tr>`}).join('');if(!partyCode.value&&!editingPartyId)partyCode.value=nextPartyCode();if(!paymentDate.value)paymentDate.value=todayISO()}
function cancelParty(){editingPartyId=null;partyForm.reset();partyCode.value=nextPartyCode();partyFormTitle.textContent='Add Party / Customer';partySaveBtn.textContent='Save Party';cancelPartyEdit.style.display='none'}
partyForm.onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(partyForm)),name=String(d.party_name||'').trim();if(!name)return;if(state.parties.some(p=>p.id!==editingPartyId&&String(p.party_name||'').trim().toLowerCase()===name.toLowerCase()))return alert('This party/customer already exists.');const obj={...d,party_name:name,opening_balance:+d.opening_balance||0};if(editingPartyId)Object.assign(byId(state.parties,editingPartyId),obj);else state.parties.push({id:uid(state.parties),...obj});save();cancelParty();renderAll()};
cancelPartyEdit.onclick=cancelParty;
window.editParty=id=>{const p=byId(state.parties,id);if(!p)return;editingPartyId=id;partyFormTitle.textContent='Edit Party / Customer';partySaveBtn.textContent='Update Party';cancelPartyEdit.style.display='inline-block';['party_code','party_name','phone','address','pan_vat','opening_balance'].forEach(k=>partyForm[k].value=p[k]??'');window.scrollTo({top:document.getElementById('parties').offsetTop||0,behavior:'smooth'})};
window.delParty=id=>{const p=byId(state.parties,id);if(!p)return;if(salesForParty(p).length||state.payments.some(x=>String(x.party_id)===String(id)))return alert('This party has sales/payment transactions and cannot be deleted. Edit it instead.');if(confirm('Delete this party/customer?')){state.parties=state.parties.filter(x=>x.id!==id);save();renderAll()}};
window.viewPartyLedger=id=>{const p=byId(state.parties,id);if(!p)return;const sales=salesForParty(p),pays=state.payments.filter(x=>String(x.party_id)===String(id));let rows=[...sales.map(s=>({date:s.sale_date,type:'Bill '+(s.bill_no||''),debit:saleDue(s),credit:0,note:s.payment_type||''})),...pays.map(x=>({date:x.payment_date,type:'Payment',debit:0,credit:+x.amount||0,note:(x.mode||'')+(x.reference?' • '+x.reference:'')}))].sort((a,b)=>a.date.localeCompare(b.date));let bal=+p.opening_balance||0,html=`<tr><td>-</td><td>Opening Due</td><td>${money(bal)}</td><td>-</td><td>${money(bal)}</td></tr>`;rows.forEach(r=>{bal+=r.debit-r.credit;html+=`<tr><td>${esc(r.date)}</td><td>${esc(r.type)}<br><small>${esc(r.note)}</small></td><td>${r.debit?money(r.debit):'-'}</td><td>${r.credit?money(r.credit):'-'}</td><td><b>${money(Math.max(0,bal))}</b></td></tr>`});const w=window.open('','_blank','width=780,height=720');if(!w)return alert('Please allow pop-ups.');w.document.write(`<!doctype html><html><head><title>${esc(p.party_name)} Ledger</title><style>body{font-family:Arial;margin:25px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #777;padding:7px}h2{margin-bottom:3px}.right{text-align:right}</style></head><body><h2>MAIKOT COMPUTER & STATIONERY</h2><p><b>Party Ledger:</b> ${esc(p.party_name)} | ${esc(p.phone||'')}<br><b>Current Due:</b> ${money(partyDue(p))}</p><table><tr><th>Date</th><th>Details</th><th>Due Added</th><th>Payment</th><th>Balance</th></tr>${html}</table><p><button onclick="window.print()">Print Ledger</button></p></body></html>`);w.document.close()};
paymentForm.onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(paymentForm)),pid=+d.party_id,amount=+d.amount||0,p=byId(state.parties,pid);if(!p||amount<=0)return alert('Select party and enter received amount.');const due=partyDue(p);if(amount>due&&due>0&&!confirm(`Received amount ${money(amount)} is more than current due ${money(due)}. Save anyway?`))return;state.payments.push({id:uid(state.payments),party_id:pid,payment_date:d.payment_date||todayISO(),amount,mode:d.mode||'Cash',reference:String(d.reference||'').trim(),bank_wallet:String(d.bank_wallet||'').trim(),note:String(d.note||'').trim()});save();paymentForm.reset();paymentDate.value=todayISO();renderAll()};
function syncPartyToBill(){const p=byId(state.parties,+billPartySelect.value);if(p){customerName.value=p.party_name||'';customerPhone.value=p.phone||'';customerAddress.value=p.address||'';customerPan.value=p.pan_vat||''}else{customerName.value='';customerPhone.value='';customerAddress.value='';customerPan.value=''}}
billPartySelect.onchange=syncPartyToBill;
function billPaymentPreview(){const total=billCalc().total,raw=billPaidAmount.value,mode=paymentType.value;let paid=raw===''?(mode==='Credit'?0:total):Math.max(0,+raw||0);paid=Math.min(total,paid);billPaidView.textContent=money(paid);billDueView.textContent=money(Math.max(0,total-paid))}
[billDiscount,vatEnabled,vatRate,billPaidAmount].forEach(x=>x.addEventListener('input',billPaymentPreview));paymentType.addEventListener('change',()=>{billPaidAmount.placeholder=paymentType.value==='Credit'?'Blank = Rs. 0 paid now':'Blank = full bill amount';billPaymentPreview()});
const _renderBill=renderBill;renderBill=function(){_renderBill();billPaymentPreview()};
renderSales=function(){salesBody.innerHTML=[...state.sales].reverse().map(s=>{const items=s.items||[],names=items.map(i=>byId(state.products,i.product_id)?.product_name||'').join(', '),paid=salePaid(s),due=saleDue(s);return `<tr><td>${esc(s.bill_no||'Old Sale')}</td><td>${esc(s.sale_date||'')}</td><td>${esc(s.customer_name||'Cash Customer')}</td><td>${esc(s.payment_type||'Cash')}${s.payment_reference?`<br><small>${esc(s.payment_reference)}</small>`:''}</td><td>${esc(names)}</td><td>${money(saleVat(s))}</td><td>${money(paid)}</td><td><b>${money(due)}</b></td><td><b>${money(saleTotal(s))}</b></td><td>${s.bill_no?`<button onclick="printBill(${s.id})">A5 Print</button>`:''}</td></tr>`}).join('')};
saveBillBtn.onclick=()=>{if(!billCart.length)return alert('Add at least one item.');for(const i of billCart)if(i.qty>currentStock(i.product_id))return alert('Not enough stock for one or more bill items.');const c=billCalc(),mode=paymentType.value,raw=billPaidAmount.value;let paid=raw===''?(mode==='Credit'?0:c.total):Math.max(0,+raw||0);paid=Math.min(c.total,paid);const due=Math.max(0,c.total-paid),party=byId(state.parties,+billPartySelect.value);if(due>0&&!party)return alert('For Credit/partial payment, first select a saved Party / Customer so the due can be tracked.');const s={id:uid(state.sales),bill_no:nextBill(),sale_date:billDate.value||todayISO(),party_id:party?.id||null,customer_name:(party?.party_name||customerName.value.trim()||'Cash Customer'),customer_phone:(party?.phone||customerPhone.value.trim()),customer_address:(party?.address||customerAddress.value.trim()),customer_pan:(party?.pan_vat||customerPan.value.trim()),payment_type:mode,payment_reference:billPaymentRef.value.trim(),bank_wallet:billBankWallet.value.trim(),paid_amount:paid,due_amount:due,discount:c.disc,vat_enabled:vatEnabled.checked,vat_rate:vatEnabled.checked?(+vatRate.value||0):0,vat_amount:c.vat,items:billCart.map(i=>({...i}))};state.sales.push(s);save();billCart=[];billPartySelect.value='';customerName.value='';customerPhone.value='';customerAddress.value='';customerPan.value='';billPaidAmount.value='';billPaymentRef.value='';billBankWallet.value='';billDiscount.value=0;vatEnabled.checked=false;paymentType.value='Cash';renderAll();printBill(s.id)};
window.printBill=id=>{const s=byId(state.sales,id);if(!s)return;const rows=(s.items||[]).map((i,n)=>{const p=byId(state.products,i.product_id);return `<tr><td>${n+1}</td><td>${esc(p?.product_name||'')}</td><td class="num">${i.qty} ${esc(p?.unit||'')}</td><td class="num">${Number(i.rate).toFixed(2)}</td><td class="num">${Number(i.qty*i.rate).toFixed(2)}</td></tr>`}).join(''),w=window.open('','_blank','width=650,height=850');if(!w)return alert('Please allow pop-ups.');w.document.write(`<!doctype html><html><head><title>${esc(s.bill_no)}</title><style>@page{size:A5 portrait;margin:9mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#111;margin:0;font-size:11px}h1{text-align:center;font-size:19px;margin:0}.center{text-align:center;margin:2px}.title{text-align:center;font-size:14px;font-weight:bold;border-top:1px solid #333;border-bottom:1px solid #333;padding:5px;margin:8px 0}.meta{display:grid;grid-template-columns:1fr 1fr;gap:3px 12px}table{width:100%;border-collapse:collapse;margin-top:8px}th,td{border:1px solid #444;padding:5px}.num{text-align:right}.totals{width:62%;margin-left:auto;margin-top:8px}.totals div{display:flex;justify-content:space-between;padding:2px}.grand{font-weight:bold;border-top:1px solid #333;padding-top:5px!important}.due{font-weight:bold}.footer{text-align:center;margin-top:18px}@media print{button{display:none}}</style></head><body><h1>MAIKOT COMPUTER & STATIONERY</h1><p class="center">Sugamtol, Dhading</p><p class="center">Contact: 010-590058, 9849024694</p><div class="title">SALES BILL</div><div class="meta"><div><b>Bill:</b> ${esc(s.bill_no)}</div><div><b>Date:</b> ${esc(s.sale_date)}</div><div><b>Party:</b> ${esc(s.customer_name)}</div><div><b>Phone:</b> ${esc(s.customer_phone||'-')}</div><div><b>Address:</b> ${esc(s.customer_address||'-')}</div><div><b>PAN/VAT:</b> ${esc(s.customer_pan||'-')}</div></div><table><tr><th>#</th><th>Particulars</th><th>Qty</th><th>Rate</th><th>Amount</th></tr>${rows}</table><div class="totals"><div><span>Subtotal</span><b>${money(saleSubtotal(s))}</b></div><div><span>Discount</span><b>${money(s.discount)}</b></div><div><span>Taxable</span><b>${money(saleTaxable(s))}</b></div>${s.vat_enabled?`<div><span>VAT (${s.vat_rate}%)</span><b>${money(saleVat(s))}</b></div>`:''}<div class="grand"><span>Grand Total</span><span>${money(saleTotal(s))}</span></div><div><span>Paid</span><span>${money(salePaid(s))}</span></div><div class="due"><span>Due</span><span>${money(saleDue(s))}</span></div><div><span>Payment</span><span>${esc(s.payment_type||'Cash')}</span></div>${s.payment_reference?`<div><span>Reference</span><span>${esc(s.payment_reference)}</span></div>`:''}${s.bank_wallet?`<div><span>Bank/Wallet</span><span>${esc(s.bank_wallet)}</span></div>`:''}</div><p class="footer">Thank you for your business.</p><p class="center"><button onclick="window.print()">Print A5 Bill</button></p></body></html>`);w.document.close()};
const _renderAll=renderAll;renderAll=function(){_renderAll();renderPartySelects();renderParties();billPaymentPreview()};
cancelParty();renderAll();

/* v2.0 data safety: disable sample overwrite, add backup/restore, and protect reset. */
(function setupDataSafety(){
  if(typeof loadSampleBtn!=='undefined'&&loadSampleBtn){loadSampleBtn.onclick=null;loadSampleBtn.style.display='none';}
  const box=document.querySelector('#dashboard .box');
  if(!box)return;
  const notice=box.querySelector('.notice');
  if(notice)notice.innerHTML='<b>Data Safety:</b> Your business data is stored in this browser. Download a backup regularly, especially before browser cleanup or device change.';
  let tools=document.getElementById('dataSafetyTools');
  if(!tools){
    tools=document.createElement('div');tools.id='dataSafetyTools';tools.className='actions';
    tools.innerHTML='<button class="primary" id="backupDataBtn" type="button">⬇ Backup Data</button><button class="primary" id="restoreDataBtn" type="button">⬆ Restore Data</button><input id="restoreDataFile" type="file" accept="application/json,.json" style="display:none"><button id="safeResetBtn" type="button" style="background:#8b2f2f;color:#fff;border:0;padding:10px 16px;border-radius:8px;cursor:pointer">Reset All Data</button>';
    box.appendChild(tools);
  }
  if(typeof resetBtn!=='undefined'&&resetBtn){resetBtn.onclick=null;resetBtn.style.display='none';}
  const backupBtn=document.getElementById('backupDataBtn'),restoreBtn=document.getElementById('restoreDataBtn'),restoreFile=document.getElementById('restoreDataFile'),safeResetBtn=document.getElementById('safeResetBtn');
  backupBtn.onclick=()=>{
    const payload={...state,_backup_meta:{app:'Maikot Business Manager',storage_key:KEY,created_at:new Date().toISOString(),version:'2.0'}};
    const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a'),d=todayISO();
    a.href=URL.createObjectURL(blob);a.download=`Maikot-Business-Backup-${d}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000);
  };
  restoreBtn.onclick=()=>restoreFile.click();
  restoreFile.onchange=()=>{
    const f=restoreFile.files&&restoreFile.files[0];if(!f)return;const r=new FileReader();
    r.onload=()=>{try{const d=JSON.parse(r.result);for(const k of ['products','suppliers','purchases','sales'])if(!Array.isArray(d[k]))throw new Error(`Missing or invalid ${k} array`);d.parties=Array.isArray(d.parties)?d.parties:[];d.payments=Array.isArray(d.payments)?d.payments:[];delete d._backup_meta;const summary=`Products: ${d.products.length}\nSuppliers: ${d.suppliers.length}\nPurchases: ${d.purchases.length}\nSales: ${d.sales.length}\nParties: ${d.parties.length}\nPayments: ${d.payments.length}`;if(!confirm('Restore this backup?\n\n'+summary+'\n\nCurrent browser data will be replaced.'))return;localStorage.setItem(KEY,JSON.stringify(d));alert('Restore successful. The page will reload now.');location.reload()}catch(err){alert('Restore failed: '+err.message)}};r.readAsText(f);restoreFile.value='';
  };
  safeResetBtn.onclick=()=>{
    const typed=prompt('DANGER: This deletes ALL business data in this browser.\n\nType DELETE ALL exactly to continue.');
    if(typed!=='DELETE ALL')return alert('Reset cancelled. No data was deleted.');
    if(!confirm('Final confirmation: permanently delete Products, Suppliers, Purchases, Sales, Parties and Payments?'))return;
    state.products=[];state.suppliers=[];state.purchases=[];state.sales=[];state.parties=[];state.payments=[];billCart=[];save();cancelProduct();cancelSupplier();cancelPurchase();cancelParty();renderAll();alert('All browser data has been reset.');
  };
})();